#ifndef TAFFY_UGUI_H
#define TAFFY_UGUI_H

#pragma once

/* Generated by cbindgen from the production tu_* ABI. Do not edit by hand. */

#include <stdarg.h>
#include <stdbool.h>
#include <stdint.h>
#include <stdlib.h>

#define TU_ENUM_I32(name, ...) \
  enum name __VA_ARGS__; /* declaration helper intentionally unused */

enum TuStatus
#ifdef __cplusplus
  : int32_t
#endif
 { TuStatus_Ok=0, TuStatus_NullPointer=-1, TuStatus_InvalidContext=-2, TuStatus_InvalidNode=-3, TuStatus_InvalidResource=-4, TuStatus_InvalidEnum=-5, TuStatus_InvalidCount=-6, TuStatus_InvalidNumber=-7, TuStatus_InvalidValue=-8, TuStatus_Capacity=-9, TuStatus_WrongThread=-10, TuStatus_RegistryBusy=-11, TuStatus_Engine=-12, TuStatus_InternalPanic=-13 };
#ifndef __cplusplus
typedef int32_t TuStatus;
#endif

enum TuValueKind
#ifdef __cplusplus
  : int32_t
#endif
 { TuValueKind_Auto=0, TuValueKind_Length=1, TuValueKind_Percent=2, TuValueKind_Calc=3 };
#ifndef __cplusplus
typedef int32_t TuValueKind;
#endif

enum TuDisplay
#ifdef __cplusplus
  : int32_t
#endif
 { TuDisplay_None=0, TuDisplay_Flex=1, TuDisplay_Grid=2, TuDisplay_Block=3, TuDisplay_FlowRoot=4 };
#ifndef __cplusplus
typedef int32_t TuDisplay;
#endif

enum TuBoxSizing
#ifdef __cplusplus
  : int32_t
#endif
 { TuBoxSizing_BorderBox=0, TuBoxSizing_ContentBox=1 };
#ifndef __cplusplus
typedef int32_t TuBoxSizing;
#endif

enum TuDirection
#ifdef __cplusplus
  : int32_t
#endif
 { TuDirection_Ltr=0, TuDirection_Rtl=1 };
#ifndef __cplusplus
typedef int32_t TuDirection;
#endif

enum TuOverflow
#ifdef __cplusplus
  : int32_t
#endif
 { TuOverflow_Visible=0, TuOverflow_Clip=1, TuOverflow_Hidden=2, TuOverflow_Scroll=3 };
#ifndef __cplusplus
typedef int32_t TuOverflow;
#endif

enum TuPosition
#ifdef __cplusplus
  : int32_t
#endif
 { TuPosition_Relative=0, TuPosition_Absolute=1 };
#ifndef __cplusplus
typedef int32_t TuPosition;
#endif

enum TuFlexDirection
#ifdef __cplusplus
  : int32_t
#endif
 { TuFlexDirection_Row=0, TuFlexDirection_Column=1, TuFlexDirection_RowReverse=2, TuFlexDirection_ColumnReverse=3 };
#ifndef __cplusplus
typedef int32_t TuFlexDirection;
#endif

enum TuFlexWrap
#ifdef __cplusplus
  : int32_t
#endif
 { TuFlexWrap_NoWrap=0, TuFlexWrap_Wrap=1, TuFlexWrap_WrapReverse=2 };
#ifndef __cplusplus
typedef int32_t TuFlexWrap;
#endif

enum TuAlign
#ifdef __cplusplus
  : int32_t
#endif
 { TuAlign_Unset=-1, TuAlign_Start=0, TuAlign_End=1, TuAlign_Center=2, TuAlign_Stretch=3, TuAlign_Baseline=4, TuAlign_FlexStart=5, TuAlign_FlexEnd=6, TuAlign_SelfStart=7, TuAlign_SelfEnd=8, TuAlign_SafeStart=9, TuAlign_SafeEnd=10, TuAlign_SafeCenter=11, TuAlign_SafeFlexStart=12, TuAlign_SafeFlexEnd=13, TuAlign_SafeSelfStart=14, TuAlign_SafeSelfEnd=15 };
#ifndef __cplusplus
typedef int32_t TuAlign;
#endif

enum TuAlignContent
#ifdef __cplusplus
  : int32_t
#endif
 { TuAlignContent_Unset=-1, TuAlignContent_Start=0, TuAlignContent_End=1, TuAlignContent_Center=2, TuAlignContent_Stretch=3, TuAlignContent_SpaceBetween=4, TuAlignContent_SpaceAround=5, TuAlignContent_SpaceEvenly=6, TuAlignContent_FlexStart=7, TuAlignContent_FlexEnd=8, TuAlignContent_SafeStart=9, TuAlignContent_SafeEnd=10, TuAlignContent_SafeCenter=11, TuAlignContent_SafeFlexStart=12, TuAlignContent_SafeFlexEnd=13 };
#ifndef __cplusplus
typedef int32_t TuAlignContent;
#endif

enum TuTextAlign
#ifdef __cplusplus
  : int32_t
#endif
 { TuTextAlign_Auto=0, TuTextAlign_LegacyLeft=1, TuTextAlign_LegacyRight=2, TuTextAlign_LegacyCenter=3 };
#ifndef __cplusplus
typedef int32_t TuTextAlign;
#endif

enum TuFloatMode
#ifdef __cplusplus
  : int32_t
#endif
 { TuFloatMode_None=0, TuFloatMode_Left=1, TuFloatMode_Right=2 };
#ifndef __cplusplus
typedef int32_t TuFloatMode;
#endif

enum TuClearMode
#ifdef __cplusplus
  : int32_t
#endif
 { TuClearMode_None=0, TuClearMode_Left=1, TuClearMode_Right=2, TuClearMode_Both=3 };
#ifndef __cplusplus
typedef int32_t TuClearMode;
#endif

enum TuGridAutoFlow
#ifdef __cplusplus
  : int32_t
#endif
 { TuGridAutoFlow_Row=0, TuGridAutoFlow_Column=1, TuGridAutoFlow_RowDense=2, TuGridAutoFlow_ColumnDense=3 };
#ifndef __cplusplus
typedef int32_t TuGridAutoFlow;
#endif

enum TuGridPlacementKind
#ifdef __cplusplus
  : int32_t
#endif
 { TuGridPlacementKind_Auto=0, TuGridPlacementKind_Line=1, TuGridPlacementKind_Span=2, TuGridPlacementKind_NamedLine=3, TuGridPlacementKind_NamedSpan=4 };
#ifndef __cplusplus
typedef int32_t TuGridPlacementKind;
#endif

enum TuCalcOp
#ifdef __cplusplus
  : int32_t
#endif
 { TuCalcOp_Length=0, TuCalcOp_Percent=1, TuCalcOp_Add=2, TuCalcOp_Sub=3, TuCalcOp_Scale=4, TuCalcOp_Min=5, TuCalcOp_Max=6, TuCalcOp_Clamp=7 };
#ifndef __cplusplus
typedef int32_t TuCalcOp;
#endif

enum TuGridTrackKind
#ifdef __cplusplus
  : int32_t
#endif
 { TuGridTrackKind_Auto=0, TuGridTrackKind_Length=1, TuGridTrackKind_Percent=2, TuGridTrackKind_Fraction=3, TuGridTrackKind_MinMax=4, TuGridTrackKind_MinContent=5, TuGridTrackKind_MaxContent=6, TuGridTrackKind_Calc=7, TuGridTrackKind_Repeat=8 };
#ifndef __cplusplus
typedef int32_t TuGridTrackKind;
#endif

enum TuGridRepeatMode
#ifdef __cplusplus
  : int32_t
#endif
 { TuGridRepeatMode_Count=0, TuGridRepeatMode_AutoFill=1, TuGridRepeatMode_AutoFit=2 };
#ifndef __cplusplus
typedef int32_t TuGridRepeatMode;
#endif

enum TuGridAxis
#ifdef __cplusplus
  : int32_t
#endif
 { TuGridAxis_Row=0, TuGridAxis_Column=1 };
#ifndef __cplusplus
typedef int32_t TuGridAxis;
#endif

typedef uint64_t TuContextHandle;
typedef uint64_t TuResourceHandle;
typedef uint64_t TuNodeHandle;

typedef struct TuValue { int32_t kind; float value; TuResourceHandle resource; } TuValue;
typedef struct TuStringView { const uint8_t *data; uint32_t len; } TuStringView;
typedef struct TuGridPlacement { int32_t kind; int32_t line; uint32_t span; int32_t occurrence; struct TuStringView name; } TuGridPlacement;
typedef struct TuStyle {
  int32_t display; int32_t box_sizing; int32_t direction; int32_t overflow_x; int32_t overflow_y; float scrollbar_width; int32_t position;
  struct TuValue inset_left,inset_right,inset_top,inset_bottom,width,height,min_width,min_height,max_width,max_height;
  float aspect_ratio;
  struct TuValue margin_left,margin_right,margin_top,margin_bottom,padding_left,padding_right,padding_top,padding_bottom,border_left,border_right,border_top,border_bottom;
  int32_t flex_direction; int32_t flex_wrap; struct TuValue flex_basis; float flex_grow; float flex_shrink;
  int32_t align_items,align_self,align_content,justify_content,justify_items,justify_self; struct TuValue gap_x,gap_y;
  uint8_t item_is_table; uint8_t item_is_replaced; int32_t float_mode,clear_mode,text_align,grid_auto_flow;
  struct TuGridPlacement grid_row_start,grid_row_end,grid_column_start,grid_column_end;
} TuStyle;
typedef struct TuStyleUpdate { TuNodeHandle node; struct TuStyle style; } TuStyleUpdate;
typedef struct TuChildrenUpdate { TuNodeHandle parent; const TuNodeHandle *children; uint32_t child_count; } TuChildrenUpdate;
typedef struct TuMeasurementSample { float available_width,width,height; } TuMeasurementSample;
typedef struct TuMeasurement { float min_width,min_height,max_width,max_height,preferred_width,preferred_height,aspect_ratio; uint8_t is_replaced; const struct TuMeasurementSample *samples; uint32_t sample_count; } TuMeasurement;
typedef struct TuMeasurementUpdate { TuNodeHandle node; struct TuMeasurement measurement; uint8_t has_measurement; } TuMeasurementUpdate;
typedef struct TuCalcSpec { int32_t op; float value; const TuResourceHandle *operands; uint32_t operand_count; } TuCalcSpec;
typedef struct TuGridTrack { int32_t kind; float value; TuResourceHandle resource; int32_t min_kind; float min_value; TuResourceHandle min_resource; int32_t max_kind; float max_value; TuResourceHandle max_resource; int32_t repeat_mode; uint32_t repeat_count; const struct TuGridTrack *repeat_tracks; uint32_t repeat_track_count; } TuGridTrack;
typedef struct TuNamedGridLine { int32_t axis; uint32_t line_index; struct TuStringView name; } TuNamedGridLine;
typedef struct TuGridArea { struct TuStringView name; uint32_t row_start,row_end,column_start,column_end; } TuGridArea;
typedef struct TuGridTemplate { const struct TuGridTrack *rows; uint32_t row_count; const struct TuGridTrack *columns; uint32_t column_count; const struct TuGridTrack *auto_rows; uint32_t auto_row_count; const struct TuGridTrack *auto_columns; uint32_t auto_column_count; const struct TuNamedGridLine *named_lines; uint32_t named_line_count; const struct TuGridArea *areas; uint32_t area_count,area_rows,area_columns; } TuGridTemplate;
typedef struct TuGridInfo { uint32_t negative_implicit_rows,explicit_rows,positive_implicit_rows,negative_implicit_columns,explicit_columns,positive_implicit_columns,row_track_count,column_track_count,item_count; } TuGridInfo;
typedef struct TuGridItemInfo { uint32_t row_start,row_end,column_start,column_end; } TuGridItemInfo;
typedef struct TuLayout { TuNodeHandle node; uint32_t order; float x,y,width,height,content_width,content_height,scroll_width,scroll_height; } TuLayout;

#ifdef __cplusplus
extern "C" {
#endif
uint32_t tu_get_abi_version(void); uint32_t tu_get_abi_stage(void); uint64_t tu_get_capabilities(void); uint32_t tu_get_taffy_version_packed(void); uint32_t tu_get_build_version_length(void);
int32_t tu_copy_build_version(uint8_t*,uint32_t,uint32_t*); uint32_t tu_get_last_error_length(void); int32_t tu_copy_last_error(uint8_t*,uint32_t,uint32_t*);
int32_t tu_context_create(TuContextHandle*); int32_t tu_context_destroy(TuContextHandle); int32_t tu_context_clear(TuContextHandle);
int32_t tu_node_create(TuContextHandle,const struct TuStyle*,TuNodeHandle*); int32_t tu_node_remove(TuContextHandle,TuNodeHandle); int32_t tu_node_set_style(TuContextHandle,TuNodeHandle,const struct TuStyle*); int32_t tu_nodes_set_styles(TuContextHandle,const struct TuStyleUpdate*,uint32_t);
int32_t tu_node_set_children(TuContextHandle,TuNodeHandle,const TuNodeHandle*,uint32_t); int32_t tu_nodes_set_children(TuContextHandle,const struct TuChildrenUpdate*,uint32_t); int32_t tu_node_mark_dirty(TuContextHandle,TuNodeHandle); int32_t tu_node_is_dirty(TuContextHandle,TuNodeHandle,uint8_t*);
int32_t tu_node_set_measurement(TuContextHandle,TuNodeHandle,const struct TuMeasurement*); int32_t tu_nodes_set_measurements(TuContextHandle,const struct TuMeasurementUpdate*,uint32_t);
int32_t tu_calc_create(TuContextHandle,const struct TuCalcSpec*,TuResourceHandle*); int32_t tu_calc_remove(TuContextHandle,TuResourceHandle);
int32_t tu_node_set_grid_template(TuContextHandle,TuNodeHandle,const struct TuGridTemplate*); int32_t tu_get_grid_info(TuContextHandle,TuNodeHandle,struct TuGridInfo*); int32_t tu_get_grid_track_sizes(TuContextHandle,TuNodeHandle,int32_t,float*,uint32_t,uint32_t*); int32_t tu_get_grid_items(TuContextHandle,TuNodeHandle,struct TuGridItemInfo*,uint32_t,uint32_t*); int32_t tu_get_grid_gutters(TuContextHandle,TuNodeHandle,int32_t,float*,uint32_t,uint32_t*);
int32_t tu_compute_layout(TuContextHandle,TuNodeHandle,float,float); int32_t tu_get_layout(TuContextHandle,TuNodeHandle,struct TuLayout*); int32_t tu_get_layouts_bulk(TuContextHandle,const TuNodeHandle*,uint32_t,struct TuLayout*,uint32_t,uint32_t*);
#ifdef __cplusplus
}
#endif
#endif
