/* Generated by cbindgen from the production tu_* ABI. Do not edit by hand. */
#ifndef TAFFY_UGUI_H
#define TAFFY_UGUI_H
#pragma once
#include <stdint.h>

typedef uint64_t TuContextHandle;
typedef uint64_t TuNodeHandle;
typedef uint64_t TuResourceHandle;


typedef enum TuValueKind { TuValueKind_Auto=0, TuValueKind_Length=1, TuValueKind_Percent=2, TuValueKind_Calc=3 } TuValueKind;
typedef enum TuDisplay { TuDisplay_None=0, TuDisplay_Flex=1, TuDisplay_Grid=2, TuDisplay_Block=3, TuDisplay_FlowRoot=4 } TuDisplay;
typedef enum TuBoxSizing { TuBoxSizing_BorderBox=0, TuBoxSizing_ContentBox=1 } TuBoxSizing;
typedef enum TuDirection { TuDirection_Ltr=0, TuDirection_Rtl=1 } TuDirection;
typedef enum TuOverflow { TuOverflow_Visible=0, TuOverflow_Clip=1, TuOverflow_Hidden=2, TuOverflow_Scroll=3 } TuOverflow;
typedef enum TuPosition { TuPosition_Relative=0, TuPosition_Absolute=1 } TuPosition;
typedef enum TuFlexDirection { TuFlexDirection_Row=0, TuFlexDirection_Column=1, TuFlexDirection_RowReverse=2, TuFlexDirection_ColumnReverse=3 } TuFlexDirection;
typedef enum TuFlexWrap { TuFlexWrap_NoWrap=0, TuFlexWrap_Wrap=1, TuFlexWrap_WrapReverse=2 } TuFlexWrap;
typedef enum TuAlign { TuAlign_Unset=-1, TuAlign_Start=0, TuAlign_End=1, TuAlign_Center=2, TuAlign_Stretch=3, TuAlign_Baseline=4, TuAlign_FlexStart=5, TuAlign_FlexEnd=6, TuAlign_SelfStart=7, TuAlign_SelfEnd=8, TuAlign_SafeStart=9, TuAlign_SafeEnd=10, TuAlign_SafeCenter=11, TuAlign_SafeFlexStart=12, TuAlign_SafeFlexEnd=13, TuAlign_SafeSelfStart=14, TuAlign_SafeSelfEnd=15 } TuAlign;
typedef enum TuAlignContent { TuAlignContent_Unset=-1, TuAlignContent_Start=0, TuAlignContent_End=1, TuAlignContent_Center=2, TuAlignContent_Stretch=3, TuAlignContent_SpaceBetween=4, TuAlignContent_SpaceAround=5, TuAlignContent_SpaceEvenly=6, TuAlignContent_FlexStart=7, TuAlignContent_FlexEnd=8, TuAlignContent_SafeStart=9, TuAlignContent_SafeEnd=10, TuAlignContent_SafeCenter=11, TuAlignContent_SafeFlexStart=12, TuAlignContent_SafeFlexEnd=13 } TuAlignContent;
typedef enum TuTextAlign { TuTextAlign_Auto=0, TuTextAlign_LegacyLeft=1, TuTextAlign_LegacyRight=2, TuTextAlign_LegacyCenter=3 } TuTextAlign;
typedef enum TuFloatMode { TuFloatMode_None=0, TuFloatMode_Left=1, TuFloatMode_Right=2 } TuFloatMode;
typedef enum TuClearMode { TuClearMode_None=0, TuClearMode_Left=1, TuClearMode_Right=2, TuClearMode_Both=3 } TuClearMode;
typedef enum TuGridAutoFlow { TuGridAutoFlow_Row=0, TuGridAutoFlow_Column=1, TuGridAutoFlow_RowDense=2, TuGridAutoFlow_ColumnDense=3 } TuGridAutoFlow;
typedef enum TuGridPlacementKind { TuGridPlacementKind_Auto=0, TuGridPlacementKind_Line=1, TuGridPlacementKind_Span=2, TuGridPlacementKind_NamedLine=3, TuGridPlacementKind_NamedSpan=4 } TuGridPlacementKind;
typedef enum TuCalcOp { TuCalcOp_Length=0, TuCalcOp_Percent=1, TuCalcOp_Add=2, TuCalcOp_Sub=3, TuCalcOp_Scale=4, TuCalcOp_Min=5, TuCalcOp_Max=6, TuCalcOp_Clamp=7 } TuCalcOp;
typedef enum TuGridTrackKind { TuGridTrackKind_Auto=0, TuGridTrackKind_Length=1, TuGridTrackKind_Percent=2, TuGridTrackKind_Fraction=3, TuGridTrackKind_MinMax=4, TuGridTrackKind_MinContent=5, TuGridTrackKind_MaxContent=6, TuGridTrackKind_Calc=7, TuGridTrackKind_Repeat=8 } TuGridTrackKind;
typedef enum TuGridRepeatMode { TuGridRepeatMode_Count=0, TuGridRepeatMode_AutoFill=1, TuGridRepeatMode_AutoFit=2 } TuGridRepeatMode;
typedef enum TuGridAxis { TuGridAxis_Row=0, TuGridAxis_Column=1 } TuGridAxis;

typedef enum TuStatus {
  TuStatus_Ok = 0, TuStatus_NullPointer = -1, TuStatus_InvalidContext = -2,
  TuStatus_InvalidNode = -3, TuStatus_InvalidResource = -4, TuStatus_InvalidEnum = -5,
  TuStatus_InvalidCount = -6, TuStatus_InvalidNumber = -7, TuStatus_InvalidValue = -8,
  TuStatus_Capacity = -9, TuStatus_WrongThread = -10, TuStatus_RegistryBusy = -11,
  TuStatus_Engine = -12, TuStatus_InternalPanic = -13
} TuStatus;

typedef struct TuStringView { const uint8_t *data; uint32_t len; } TuStringView;
typedef struct TuValue { int32_t kind; float value; TuResourceHandle resource; } TuValue;
typedef struct TuGridPlacement { int32_t kind; int32_t line; uint32_t span; int32_t occurrence; TuStringView name; } TuGridPlacement;
typedef struct TuStyle {
  int32_t display, box_sizing, direction, overflow_x, overflow_y; float scrollbar_width; int32_t position;
  TuValue inset_left,inset_right,inset_top,inset_bottom,width,height,min_width,min_height,max_width,max_height; float aspect_ratio;
  TuValue margin_left,margin_right,margin_top,margin_bottom,padding_left,padding_right,padding_top,padding_bottom,border_left,border_right,border_top,border_bottom;
  int32_t flex_direction,flex_wrap; TuValue flex_basis; float flex_grow,flex_shrink; int32_t align_items,align_self,align_content,justify_content,justify_items,justify_self; TuValue gap_x,gap_y;
  uint8_t item_is_table,item_is_replaced; int32_t float_mode,clear_mode,text_align,grid_auto_flow; TuGridPlacement grid_row_start,grid_row_end,grid_column_start,grid_column_end;
} TuStyle;
typedef struct TuStyleUpdate { TuNodeHandle node; TuStyle style; } TuStyleUpdate;
typedef struct TuMeasurementSample { float available_width,width,height; } TuMeasurementSample;
typedef struct TuMeasurement { float min_width,min_height,max_width,max_height,preferred_width,preferred_height,aspect_ratio; uint8_t is_replaced; const TuMeasurementSample *samples; uint32_t sample_count; } TuMeasurement;
typedef struct TuMeasurementUpdate { TuNodeHandle node; TuMeasurement measurement; uint8_t has_measurement; } TuMeasurementUpdate;
typedef struct TuChildrenUpdate { TuNodeHandle parent; const TuNodeHandle *children; uint32_t child_count; } TuChildrenUpdate;
typedef struct TuLayout { TuNodeHandle node; uint32_t order; float x,y,width,height,content_width,content_height,scroll_width,scroll_height; } TuLayout;
typedef struct TuCalcSpec { int32_t op; float value; const TuResourceHandle *operands; uint32_t operand_count; } TuCalcSpec;
typedef struct TuGridTrack { int32_t kind; float value; TuResourceHandle resource; int32_t min_kind; float min_value; TuResourceHandle min_resource; int32_t max_kind; float max_value; TuResourceHandle max_resource; int32_t repeat_mode; uint32_t repeat_count; const struct TuGridTrack *repeat_tracks; uint32_t repeat_track_count; } TuGridTrack;
typedef struct TuNamedGridLine { int32_t axis; uint32_t line_index; TuStringView name; } TuNamedGridLine;
typedef struct TuGridArea { TuStringView name; uint32_t row_start,row_end,column_start,column_end; } TuGridArea;
typedef struct TuGridInfo { uint32_t negative_implicit_rows,explicit_rows,positive_implicit_rows,negative_implicit_columns,explicit_columns,positive_implicit_columns,row_track_count,column_track_count,item_count; } TuGridInfo;
typedef struct TuGridItemInfo { uint32_t row_start,row_end,column_start,column_end; } TuGridItemInfo;
typedef struct TuGridTemplate { const TuGridTrack *rows; uint32_t row_count; const TuGridTrack *columns; uint32_t column_count; const TuGridTrack *auto_rows; uint32_t auto_row_count; const TuGridTrack *auto_columns; uint32_t auto_column_count; const TuNamedGridLine *named_lines; uint32_t named_line_count; const TuGridArea *areas; uint32_t area_count,area_rows,area_columns; } TuGridTemplate;

uint32_t tu_get_abi_version(void); uint32_t tu_get_abi_stage(void); uint64_t tu_get_capabilities(void); uint32_t tu_get_taffy_version_packed(void);
uint32_t tu_get_build_version_length(void); int32_t tu_copy_build_version(uint8_t*,uint32_t,uint32_t*);
uint32_t tu_get_last_error_length(void); int32_t tu_copy_last_error(uint8_t*,uint32_t,uint32_t*);
int32_t tu_context_create(TuContextHandle*); int32_t tu_context_destroy(TuContextHandle); int32_t tu_context_clear(TuContextHandle);
int32_t tu_node_create(TuContextHandle,const TuStyle*,TuNodeHandle*); int32_t tu_node_remove(TuContextHandle,TuNodeHandle);
int32_t tu_node_set_style(TuContextHandle,TuNodeHandle,const TuStyle*); int32_t tu_nodes_set_styles(TuContextHandle,const TuStyleUpdate*,uint32_t);
int32_t tu_node_set_children(TuContextHandle,TuNodeHandle,const TuNodeHandle*,uint32_t); int32_t tu_nodes_set_children(TuContextHandle,const TuChildrenUpdate*,uint32_t);
int32_t tu_node_mark_dirty(TuContextHandle,TuNodeHandle); int32_t tu_node_is_dirty(TuContextHandle,TuNodeHandle,uint8_t*);
int32_t tu_node_set_measurement(TuContextHandle,TuNodeHandle,const TuMeasurement*); int32_t tu_nodes_set_measurements(TuContextHandle,const TuMeasurementUpdate*,uint32_t);
int32_t tu_calc_create(TuContextHandle,const TuCalcSpec*,TuResourceHandle*); int32_t tu_calc_remove(TuContextHandle,TuResourceHandle);
int32_t tu_node_set_grid_template(TuContextHandle,TuNodeHandle,const TuGridTemplate*);
int32_t tu_get_grid_info(TuContextHandle,TuNodeHandle,TuGridInfo*); int32_t tu_get_grid_track_sizes(TuContextHandle,TuNodeHandle,int32_t,float*,uint32_t,uint32_t*); int32_t tu_get_grid_gutters(TuContextHandle,TuNodeHandle,int32_t,float*,uint32_t,uint32_t*); int32_t tu_get_grid_items(TuContextHandle,TuNodeHandle,TuGridItemInfo*,uint32_t,uint32_t*);
int32_t tu_compute_layout(TuContextHandle,TuNodeHandle,float,float); int32_t tu_get_layout(TuContextHandle,TuNodeHandle,TuLayout*);
int32_t tu_get_layouts_bulk(TuContextHandle,const TuNodeHandle*,uint32_t,TuLayout*,uint32_t,uint32_t*);
#endif
